### ISSUE TITLE
Clicking "link to wallet" uses old invalid URL

### ISSUE THREAD

**Issue by 20a8vnf30** [lnbits/usermanager#18]
LNbits 0.12.2
Usermanager 0.4.0

The "link to wallet button" ![image](https://github.com/lnbits/usermanager/assets/9660062/fa3fa205-d45b-4037-9311-5e168709770a) still uses the old style "https://lnbits.domain.com/wallet?wal=[wallet_ID]" URL to load the user's page/wallet.
These URL's are no longer valid so you land at the error page.
![image](https://github.com/lnbits/usermanager/assets/9660062/59da892d-2a61-4fb5-8d43-1daf4c99b6ac)

Expected behaviour:
Clicking the link to wallet button opens that user's LNbits wallet without having to know the user's login.

**Comment by talvasconcelos** [comment]
What version of the extension is the issue related? Latest version sends correct URL `?usr=XXXX&wal=XXXX`

**Comment by 20a8vnf30** [comment]
> What version of the extension is the issue related? Latest version sends correct URL `?usr=XXXX&wal=XXXX`

Still seeing this issue in LNbits 0.12.10 and Usermanager extension 0.4.1.
The URL might be correct but you can no longer access an LNbits account through that type of URL, that feature was removed in a previous version. 
For that reason I believe the usermanager extension should no longer be presenting that URL.

**Comment by talvasconcelos** [comment]
I think you're trying to open the URL on the same browser you're already logged in. Try copying the URL and open on a fresh incognito browser window, where you're not logged in to LNbits!

**Comment by 20a8vnf30** [comment]
> I think you're trying to open the URL on the same browser you're already logged in. Try copying the URL and open on a fresh incognito browser window, where you're not logged in to LNbits!

You're right that was it.
